name: Test & Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - id: commit
      uses: pr-mpt/actions-commit-hash@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: img.conny.dev
        username: ${{ secrets.DOCKER_USER}}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push main
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: img.conny.dev/connylabs/kured-assistant:${{ steps.commit.outputs.short }}, img.conny.dev/connylabs/kured-assistant:main, img.conny.dev/connylabs/kured-assistant:latest

    - name: Build and push branches
      if: github.ref != 'refs/heads/main'
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: img.conny.dev/connylabs/kured-assistant:${{ steps.commit.outputs.short }}
